name: Deploy
description: Deploy
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      shell: bash
      working-directory: ${{ env.SERVICE_NAME }}
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      shell: bash
      working-directory: ${{ env.SERVICE_NAME }}
      run: mvn -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/DaichiMiyajima/platform-openapi-action-spring deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
